### ISSUE TITLE
`SDatePicker` - no way to disable dates

### ISSUE THREAD

**Issue by Ctepan** [soramitsu/soramitsu-js-ui-library#537]
We should add `allowedDates`/`disabledDates` prop (`(date: Date) => boolean`). `min`, `max` props(`Date`/ISO) as special case would be good too

**Comment by 0x009922** [comment]
Maybe use prop name like `dates-predicate` or `dates-filter`?

`allowedDates` and `disabledDates` are more intuitive if we pass an array of dates in them, imo. Also, if we also accept such props, I think naming like `datesInclude` & `datesExclude` might be better, because e.g. it is an established format in Rollup plugins.

If `min`/`max` are presented, they should overwrite the function predicate?

**Comment by Ctepan** [comment]
Added in https://github.com/soramitsu/soramitsu-js-ui-library/pull/547 and https://github.com/soramitsu/soramitsu-js-ui-library/pull/557
